Verschiedene Fragen sollen jeweils beantwortet werden: <br />
<ol>
    <li>Wie kann an einen speziellen QB die jeweiligen Stats (Rush/Throw) angepinnt werden?
    <li>Wie können jeweils Rankings erstellt werden?
    <li>Fokus auf Fantasy Points
        <ol>
        <li>Gegen welche Gegner macht welcher QB die besten Spiele? (2024, 2025)

# Quarterback Analysis

### Vorbereitungen

##### Pakete laden

In [2]:
import nflreadpy as nfl
import polars as pl
import numpy as np

##### Datengrundlage

In [3]:
seasons = np.arange(2003, 2026).tolist() # 2003 - 2025

In [6]:
(
    nfl.load_player_stats(seasons)
    .filter(
        (pl.col('player_display_name') == 'Josh Allen') & (pl.col('position') == "QB"))
    .select([
        'player_id', 'player_display_name', 'position', 'position_group',
        'season', 'week', 'season_type', 'team', 'opponent_team',
        'completions', 'attempts', 'passing_yards', 'passing_tds', 'passing_interceptions',
        'sacks_suffered', 'sack_yards_lost', 'sack_fumbles', 'sack_fumbles_lost',
        'passing_air_yards', 'passing_yards_after_catch', 'passing_first_downs', 'passing_epa', 'passing_cpoe', 'passing_2pt_conversions',
        'pacr',
        'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions', 'racr',
        'target_share', 'air_yards_share', 'wopr', 'special_teams_tds','misc_yards',
        'penalties', 'penalty_yards', 'fantasy_points', 'fantasy_points_ppr'
    ])
)

shape: (141, 43)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_di ┆ position ┆ position_ ┆ … ┆ penalties ┆ penalty_y ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ splay_nam ┆ ---      ┆ group     ┆   ┆ ---       ┆ ards      ┆ oints     ┆ oints_ppr │
│ str       ┆ e         ┆ str      ┆ ---       ┆   ┆ i32       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ ---       ┆          ┆ str       ┆   ┆           ┆ i32       ┆ f64       ┆ f64       │
│           ┆ str       ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-003485 ┆ Josh      ┆ QB       ┆ QB        ┆ … ┆ 0         ┆ 0         ┆ 5.56      ┆ 5.56      │
│ 7         ┆ Allen     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ Josh      ┆ QB       ┆ QB        ┆ … ┆ 0         ┆ 0         ┆ 11.8      ┆ 11.8      │
│ 7         ┆ Allen     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ Josh      ┆ QB       ┆ QB        ┆ … ┆ 0         ┆ 0         ┆ 27.74     ┆ 27.74     │
│ 7         ┆ Allen     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ Josh      ┆ QB       ┆ QB        ┆ … ┆ 0         ┆ 0         ┆ 1.94      ┆ 1.94      │
│ 7         ┆ Allen     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ Josh      ┆ QB       ┆ QB        ┆ … ┆ 1         ┆ 5         ┆ 9.18      ┆ 9.18      │
│ 7         ┆ Allen     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-003485 ┆ Josh      ┆ QB       ┆ QB        ┆ … ┆ 0         ┆ 0         ┆ 24.52     ┆ 24.52     │
│ 7         ┆ Allen     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ Josh      ┆ QB       ┆ QB        ┆ … ┆ 0         ┆ 0         ┆ 6.9       ┆ 6.9       │
│ 7         ┆ Allen     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ Josh      ┆ QB       ┆ QB        ┆ … ┆ 0         ┆ 0         ┆ 23.18     ┆ 23.18     │
│ 7         ┆ Allen     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ Josh      ┆ QB       ┆ QB        ┆ … ┆ 0         ┆ 0         ┆ 30.22     ┆ 30.22     │
│ 7         ┆ Allen     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003485 ┆ Josh      ┆ QB       ┆ QB        ┆ … ┆ 0         ┆ 0         ┆ 21.92     ┆ 21.92     │
│ 7         ┆ Allen     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
(
    nfl.load_ff_opportunity(seasons=2022, stat_type='weekly')
    .filter((pl.col('full_name') == 'Josh Allen') & (pl.col('position') == 'QB'))
    .select([
        'game_id', 'full_name', 'player_id', 'position',
        'pass_fantasy_points',  'pass_fantasy_points_exp',
        'rush_fantasy_points', 'rush_fantasy_points_exp',
        'total_fantasy_points', 'total_fantasy_points_exp',
    ])
)

shape: (18, 37)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ game_id   ┆ full_name ┆ player_id ┆ position ┆ … ┆ total_fir ┆ total_fir ┆ total_fan ┆ total_fan │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆   ┆ st_down   ┆ st_down_e ┆ tasy_poin ┆ tasy_poin │
│ str       ┆ str       ┆ str       ┆ str      ┆   ┆ ---       ┆ xp        ┆ ts        ┆ ts_exp    │
│           ┆           ┆           ┆          ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆           ┆          ┆   ┆           ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2022_01_B ┆ Josh      ┆ 00-003485 ┆ QB       ┆ … ┆ 19.0      ┆ 16.61     ┆ 31.48     ┆ 27.32     │
│ UF_LA     ┆ Allen     ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2022_02_T ┆ Josh      ┆ 00-003485 ┆ QB       ┆ … ┆ 14.0      ┆ 15.41     ┆ 29.68     ┆ 23.67     │
│ EN_BUF    ┆ Allen     ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2022_03_B ┆ Josh      ┆ 00-003485 ┆ QB       ┆ … ┆ 26.0      ┆ 29.54     ┆ 28.7      ┆ 46.37     │
│ UF_MIA    ┆ Allen     ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2022_04_B ┆ Josh      ┆ 00-003485 ┆ QB       ┆ … ┆ 19.0      ┆ 17.49     ┆ 23.52     ┆ 21.28     │
│ UF_BAL    ┆ Allen     ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2022_05_P ┆ Josh      ┆ 00-003485 ┆ QB       ┆ … ┆ 17.0      ┆ 13.14     ┆ 35.16     ┆ 25.56     │
│ IT_BUF    ┆ Allen     ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2022_15_M ┆ Josh      ┆ 00-003485 ┆ QB       ┆ … ┆ 19.0      ┆ 19.05     ┆ 37.86     ┆ 30.14     │
│ IA_BUF    ┆ Allen     ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2022_16_B ┆ Josh      ┆ 00-003485 ┆ QB       ┆ … ┆ 13.0      ┆ 11.34     ┆ 22.98     ┆ 19.89     │
│ UF_CHI    ┆ Allen     ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2022_18_N ┆ Josh      ┆ 00-003485 ┆ QB       ┆ … ┆ 13.0      ┆ 15.58     ┆ 21.76     ┆ 23.31     │
│ E_BUF     ┆ Allen     ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2022_19_M ┆ Josh      ┆ 00-003485 ┆ QB       ┆ … ┆ 18.0      ┆ 16.08     ┆ 24.08     ┆ 24.19     │
│ IA_BUF    ┆ Allen     ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2022_20_C ┆ Josh      ┆ 00-003485 ┆ QB       ┆ … ┆ 17.0      ┆ 19.12     ┆ 17.2      ┆ 26.45     │
│ IN_BUF    ┆ Allen     ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘